packages:
  - packages/*

savePrefix: ""

catalog:
  typescript: 7.0.2
  tsdown: 0.22.14
  vitest: 4.1.11
  axios: 1.19.0
  ufo: 1.6.4

allowBuilds:
  esbuild: true
  vue-demi: set this to true or false

minimumReleaseAgeExclude:
  - "@publint/pack@0.1.7"
  - publint@0.3.24
